"use client";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Copy, CheckCircle2, Upload, ArrowLeft, Info, Loader2 
} from "lucide-react";
import { createBrowserClient } from "@supabase/ssr";
import { useRouter } from "next/navigation";
import NeonInput from "@/components/NeonInput";

const supabase = createBrowserClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

export default function DepositScreen() {
  const router = useRouter();
  const [settings, setSettings] = useState<any>(null);
  const [amount, setAmount] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [copied, setCopied] = useState(false);
  const [qrLoaded, setQrLoaded] = useState(false); 

  useEffect(() => {
    const fetchSettings = async () => {
      // Thora sa delay add kiya hai taake loader ki smooth feel aaye
      const { data } = await supabase.from('admin_settings').select('*').eq('id', 1).single();
      if (data) setSettings(data);
    };
    fetchSettings();
  }, []);

  const handleCopy = () => {
    navigator.clipboard.writeText(settings?.usdt_address || "");
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      setFile(selectedFile);
      setPreviewUrl(URL.createObjectURL(selectedFile));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!file || !amount) return alert("Please enter amount and upload screenshot");
    
    setIsSubmitting(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Please login");

      const fileExt = file.name.split('.').pop();
      const fileName = `${user.id}/${Date.now()}.${fileExt}`;
      
      const { error: uploadError } = await supabase.storage
        .from('deposit-screenshots')
        .upload(fileName, file);

      if (uploadError) throw uploadError;

      const { data: { publicUrl } } = supabase.storage
        .from('deposit-screenshots')
        .getPublicUrl(fileName);

      // use RPC for creating deposit request
      const { data: rpcData, error: rpcError } = await supabase.rpc('create_deposit_request_v2', {
        p_user_id: user.id,
        p_amount: parseFloat(amount),
        p_screenshot_url: publicUrl
        // trx_id is generated by the function, no need to send from frontend
      });

      if (rpcError) throw rpcError;

      alert("Deposit Submitted! Admin will verify your payment soon.");
      router.push('/dashboard/assets');

    } catch (err: any) {
      alert("Error: " + err.message);
    } finally {
      setIsSubmitting(false);
    }
  };

  // --- Professional NexTrade Loader ---
  if (!settings) return (
    <div className="fixed inset-0 z-[999] flex flex-col items-center justify-center bg-[#0F172A]">
      <div className="relative flex items-center justify-center">
        {/* Outer Pulsing Ring */}
        <motion.div 
          animate={{ scale: [1, 1.5, 1], opacity: [0.3, 0.1, 0.3] }}
          transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
          className="absolute w-24 h-24 rounded-full bg-yellow-500/20"
        />
        {/* Inner Glowing Core */}
        <motion.div 
          animate={{ rotate: 360 }}
          transition={{ duration: 1.5, repeat: Infinity, ease: "linear" }}
          className="w-12 h-12 border-4 border-t-yellow-500 border-r-transparent border-b-transparent border-l-transparent rounded-full shadow-[0_0_15px_rgba(252,213,53,0.5)]"
        />
        <div className="absolute font-black text-yellow-500 text-sm tracking-tighter">NX</div>
      </div>
      <motion.p 
        initial={{ opacity: 0 }} animate={{ opacity: 1 }}
        className="mt-6 text-[10px] font-bold text-slate-500 uppercase tracking-[0.3em]"
      >
        Initializing Secure Gate
      </motion.p>
    </div>
  );

  return (
    <div className="min-h-screen bg-[#0F172A] text-white p-4 lg:p-8 pb-24 font-sans">
      {/* Header */}
      <div className="flex items-center justify-between mb-6 lg:mb-12">
        <button onClick={() => router.back()} className="p-3 bg-slate-900 border border-slate-800 rounded-2xl active:scale-90 transition-all">
          <ArrowLeft size={20} />
        </button>
        <h1 className="text-lg lg:text-2xl font-black uppercase tracking-widest">Deposit USDT</h1>
        <div className="w-10" /> 
      </div>

      {/* Main Content Container */}
      <div className="max-w-6xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12">
          
          {/* Left Column: QR & Address Card */}
          <div className="order-1 lg:order-1">
            <div className="bg-gradient-to-br from-slate-900 to-[#0F172A] border border-slate-800 p-6 lg:p-10 rounded-[32px] shadow-2xl relative overflow-hidden group">
              <div className="absolute top-[-20%] right-[-10%] w-40 h-40 bg-yellow-500/5 rounded-full blur-3xl group-hover:bg-yellow-500/10 transition-all" />
              
              <div className="flex flex-col items-center">
                {/* QR Code Section with Shimmer */}
                <div className="relative w-32 h-32 lg:w-48 lg:h-48 bg-white p-3 rounded-2xl mb-6 shadow-[0_0_20px_rgba(252,213,53,0.2)] overflow-hidden">
                  {!qrLoaded && (
                    <div className="absolute inset-0 bg-slate-200 animate-pulse flex items-center justify-center overflow-hidden">
                       <motion.div 
                          animate={{ x: ["-100%", "100%"] }}
                          transition={{ duration: 1.5, repeat: Infinity, ease: "linear" }}
                          className="w-full h-full bg-gradient-to-r from-transparent via-white/60 to-transparent" 
                       />
                    </div>
                  )}
                  <img 
                    src={`https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${settings.usdt_address}`} 
                    alt="Wallet QR"
                    className={`w-full h-full transition-opacity duration-700 ${qrLoaded ? 'opacity-100' : 'opacity-0'}`}
                    onLoad={() => setQrLoaded(true)}
                  />
                </div>

                <div className="text-center mb-6">
                  <span className="text-[10px] lg:text-xs bg-yellow-500/10 text-yellow-500 px-3 py-1 rounded-full font-black uppercase tracking-tighter">
                    {settings.usdt_network} Network
                  </span>
                </div>

                <div className="w-full space-y-2">
                  <label className="text-[10px] lg:text-xs text-slate-500 font-bold uppercase ml-1">Your Deposit Address</label>
                  <div className="flex items-center gap-3 bg-black/40 p-3 lg:p-4 rounded-2xl border border-slate-800/50 group-hover:border-slate-700 transition-all">
                    <p className="flex-1 text-[11px] lg:text-sm font-mono break-all text-slate-300 leading-relaxed">
                      {settings.usdt_address}
                    </p>
                    <button 
                      onClick={handleCopy} 
                      className="shrink-0 p-2 lg:p-3 bg-yellow-500 text-[#0F172A] rounded-xl active:scale-90 transition-all"
                    >
                      {copied ? <CheckCircle2 size={18} /> : <Copy size={18} />}
                    </button>
                  </div>
                </div>
              </div>

              <div className="mt-6 lg:mt-8 flex gap-3 p-3 lg:p-4 bg-yellow-500/5 rounded-2xl border border-yellow-500/10">
                <Info size={16} className="text-yellow-500 shrink-0 mt-0.5" />
                <p className="text-[10px] lg:text-xs text-slate-400 leading-normal">
                  Minimum deposit is <span className="text-white font-bold">{settings.min_deposit_amount} USDT</span>. 
                  Sending any other asset will result in permanent loss.
                </p>
              </div>
            </div>
          </div>

          {/* Right Column: Form Section */}
          <div className="order-2 lg:order-2">
            <form onSubmit={handleSubmit} className="flex flex-col space-y-8 lg:space-y-12">
              
              {/* Amount Input */}
              <div className="space-y-3">
                <NeonInput
                  label="Amount to Deposit (USDT)"
                  name="amount"
                  type="number"
                  placeholder="0.00"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  required
                />
              </div>

              {/* Screenshot Upload Area */}
              <div className="space-y-4">
                <label className="text-[10px] lg:text-xs text-slate-500 font-black uppercase tracking-widest ml-1">Payment Voucher</label>
                <div className="relative group">
                  <div className={`h-40 lg:h-52 rounded-[32px] border-2 border-dashed transition-all flex flex-col items-center justify-center overflow-hidden
                    ${previewUrl ? 'border-emerald-500 bg-emerald-500/5' : 'border-slate-800 bg-slate-900/30 group-hover:border-slate-700'}`}>
                    
                    {previewUrl ? (
                      <div className="relative w-full h-full">
                        <img src={previewUrl} alt="Preview" className="w-full h-full object-cover opacity-40" />
                        <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/40">
                          <div className="w-10 h-10 lg:w-12 lg:h-12 bg-emerald-500 rounded-full flex items-center justify-center shadow-lg shadow-emerald-500/20 mb-3">
                              <CheckCircle2 className="text-white w-5 h-5 lg:w-6 lg:h-6" />
                          </div>
                          <p className="text-[10px] lg:text-xs font-black uppercase text-emerald-400 tracking-widest">Screenshot Uploaded</p>
                          <p className="text-[9px] lg:text-xs text-slate-400 mt-1">Tap to change</p>
                        </div>
                      </div>
                    ) : (
                      <>
                        <div className="w-12 h-12 lg:w-14 lg:h-14 bg-slate-800 rounded-full flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                          <Upload className="text-slate-400 w-5 h-5 lg:w-6 lg:h-6" />
                        </div>
                        <p className="text-[11px] lg:text-sm font-black text-slate-500 tracking-wider">TAP TO UPLOAD VOUCHER</p>
                        <p className="text-[9px] lg:text-xs text-slate-600 mt-2 italic">Max size: 5MB (JPG, PNG)</p>
                      </>
                    )}
                  </div>
                  <input 
                    type="file" 
                    accept="image/*"
                    onChange={handleFileChange}
                    className="absolute inset-0 opacity-0 cursor-pointer"
                  />
                </div>
              </div>

              {/* Submit Button */}
              <div className="mt-8 lg:mt-12 pt-6 lg:pt-8 pb-8 lg:pb-10">
                <button 
                  disabled={isSubmitting}
                  className="w-full h-14 lg:h-16 bg-yellow-500 text-[#0F172A] font-black uppercase tracking-[0.2em] rounded-2xl shadow-[0_15px_40px_rgba(252,213,53,0.25)] active:scale-95 hover:bg-yellow-400 transition-all flex items-center justify-center gap-3 disabled:opacity-50"
                >
                  {isSubmitting ? (
                    <div className="flex items-center gap-2">
                      <Loader2 className="animate-spin w-4 h-4 lg:w-5 lg:h-5" />
                      <span>Processing...</span>
                    </div>
                  ) : (
                    <>CONFIRM DEPOSIT</>
                  )}
                </button>
              </div>

            </form>
          </div>
          
        </div>
      </div>
    </div>
  );
}